apiVersion: v1
kind: ConfigMap
metadata:
    name: springcloud-sample-configmap
data:
    SPRING_ZIPKIN_BASEURL: http://zipkin-service:9411/
    SPRING_PROFILES_ACTIVE: dev
    SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8000/
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver-service:9000/eureka/
