apiVersion: apps/v1
kind: Deployment
metadata:
    name: products-deployment
    labels:
        app: products
spec:
    replicas: 3
    selector:
        matchLabels:
            app: products
    template:
        metadata:
            labels:
                app: products
        spec:
            containers:
                - name: products
                  image: paolodenti/products:latest
                  ports:
                      - containerPort: 8081
                  env:
                      - name: SPRING_PROFILES_ACTIVE
                        valueFrom:
                            configMapKeyRef:
                                name: springcloud-sample-configmap
                                key: SPRING_PROFILES_ACTIVE
                      - name: SPRING_ZIPKIN_BASEURL
                        valueFrom:
                            configMapKeyRef:
                                name: springcloud-sample-configmap
                                key: SPRING_ZIPKIN_BASEURL
                      - name: SPRING_CONFIG_IMPORT
                        valueFrom:
                            configMapKeyRef:
                                name: springcloud-sample-configmap
                                key: SPRING_CONFIG_IMPORT
                      - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                        valueFrom:
                            configMapKeyRef:
                                name: springcloud-sample-configmap
                                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
    name: products-service
spec:
    selector:
        app: products
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: products-deployment
spec:
    maxReplicas: 10
    minReplicas: 3
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: products-deployment
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 75
