version: "3.8"

services:
    configserver:
        image: paolodenti/configserver:latest
        ports:
            - "8000:8000"
        environment:
            - "ENCRYPT_KEY=${ENCRYPT_KEY}"
        networks:
            - configserver-net

    eurekaserver:
        image: paolodenti/eurekaserver:latest
        ports:
            - "9000:9000"
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
        networks:
            - configserver-net

    gatewayserver:
        image: paolodenti/gatewayserver:latest
        ports:
            - "8500:8500"
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:9000/eureka/"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
        networks:
            - configserver-net

    dashboard:
        image: paolodenti/dashboard:latest
        ports:
            - "8080:8080"
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:9000/eureka/"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
        networks:
            - configserver-net

    products-1:
        image: paolodenti/products:latest
        ports:
            - "8081:8081"
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:9000/eureka/"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
        networks:
            - configserver-net

    products-2:
        image: paolodenti/products:latest
        ports:
            - "8082:8081"
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:9000/eureka/"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
        networks:
            - configserver-net

    products-3:
        image: paolodenti/products:latest
        ports:
            - "8083:8081"
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:9000/eureka/"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
        networks:
            - configserver-net

networks:
    configserver-net:
