version: "3.8"

services:
    configserver:
        image: paolodenti/configserver:latest
        networks:
            - configserver-net

    eurekaserver:
        image: paolodenti/eurekaserver:latest
        ports:
            - "8070:8070"
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8090"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
        networks:
            - configserver-net

    rest-api:
        image: paolodenti/rest-api:latest
        ports:
            - "8080:8080"
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8090"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
        networks:
            - configserver-net

    service-1-1:
        image: paolodenti/service-1:latest
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8090"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
        networks:
            - configserver-net

    service-1-2:
        image: paolodenti/service-1:latest
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8090"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
        networks:
            - configserver-net

    service-1-3:
        image: paolodenti/service-1:latest
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8090"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
        networks:
            - configserver-net

networks:
    configserver-net:
