version: "3.8"

services:
    zipkin:
        image: openzipkin/zipkin:latest
        ports:
            - "9411:9411"
        networks:
            - springcloudsample-net

    #    rabbitmq:
    #        image: rabbitmq:3-management
    #        ports:
    #            - "5672:5672"
    #            - "15672:15672"
    #        networks:
    #            - springcloudsample-net
    #
    configserver:
        image: paolodenti/configserver:latest
        ports:
            - "8000:8000"
        environment:
            - "SPRING_ZIPKIN_BASEURL=http://zipkin:9411/"
            - "SPRING_RABBITMQ_HOST=rabbitmq"
        depends_on:
            - zipkin
            # - rabbitmq
        networks:
            - springcloudsample-net

    eurekaserver:
        image: paolodenti/eurekaserver:latest
        ports:
            - "9000:9000"
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "SPRING_ZIPKIN_BASEURL=http://zipkin:9411/"
            - "SPRING_RABBITMQ_HOST=rabbitmq"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 15s
                window: 120s
        depends_on:
            - configserver
            - zipkin
            # - rabbitmq
        networks:
            - springcloudsample-net
    dashboard:
        image: paolodenti/dashboard:latest
        ports:
            - "8080:8080"
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:9000/eureka/"
            - "SPRING_ZIPKIN_BASEURL=http://zipkin:9411/"
            - "SPRING_RABBITMQ_HOST=rabbitmq"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 30s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
            - zipkin
            # - rabbitmq
        networks:
            - springcloudsample-net

    products-1:
        image: paolodenti/products:latest
        ports:
            - "8081:8081"
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:9000/eureka/"
            - "SPRING_ZIPKIN_BASEURL=http://zipkin:9411/"
            - "SPRING_RABBITMQ_HOST=rabbitmq"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 30s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
            - zipkin
            # - rabbitmq
        networks:
            - springcloudsample-net

    products-2:
        image: paolodenti/products:latest
        ports:
            - "8082:8081"
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:9000/eureka/"
            - "SPRING_ZIPKIN_BASEURL=http://zipkin:9411/"
            - "SPRING_RABBITMQ_HOST=rabbitmq"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 30s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
            - zipkin
            # - rabbitmq
        networks:
            - springcloudsample-net

    products-3:
        image: paolodenti/products:latest
        ports:
            - "8083:8081"
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:9000/eureka/"
            - "SPRING_ZIPKIN_BASEURL=http://zipkin:9411/"
            - "SPRING_RABBITMQ_HOST=rabbitmq"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 30s
                window: 120s
        depends_on:
            - configserver
            - eurekaserver
            - zipkin
            # - rabbitmq
        networks:
            - springcloudsample-net

    gatewayserver:
        image: paolodenti/gatewayserver:latest
        ports:
            - "8500:8500"
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "SPRING_CONFIG_IMPORT=configserver:http://configserver:8000"
            - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:9000/eureka/"
            - "SPRING_ZIPKIN_BASEURL=http://zipkin:9411/"
            - "SPRING_RABBITMQ_HOST=rabbitmq"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 45s
                window: 180s
        depends_on:
            - configserver
            - eurekaserver
            - zipkin
            # - rabbitmq
            - dashboard
            - products-1
            - products-2
            - products-3
        networks:
            - springcloudsample-net

networks:
    springcloudsample-net:
