global:
    scrape_interval: 5s
    evaluation_interval: 5s
scrape_configs:
    - job_name: dashboard
      metrics_path: /actuator/prometheus
      static_configs:
          - targets: ["dashboard:8080"]
    - job_name: products
      metrics_path: /actuator/prometheus
      static_configs:
          - targets: ["products-1:8081", "products-2:8081", "products-3:8081"]
